Traceback (most recent call last):
  File "/home/daineto/CostFOND/planner/planner.py", line 647, in <module>
    main(sys.argv, len(sys.argv))
  File "/home/daineto/CostFOND/planner/planner.py", line 622, in main
    solution = boand_star(domain_file, problem_file, solution_folder, use_metric=metric, use_cp_heuristic=heuristic, use_best_case_heuristic=best_heuristic, use_worst_case_heuristic=worst_heuristic, use_size_heuristic=size_heuristic, use_selector=selector)
  File "/home/daineto/CostFOND/planner/planner.py", line 508, in boand_star
    op_successors = task.get_successor_states(state)
  File "/home/daineto/CostFOND/planner/pyperplan/pyperplan/task.py", line 125, in get_successor_states
    return [(op, op.apply(state)) for op in self.operators if op.applicable(state)]
  File "/home/daineto/CostFOND/planner/pyperplan/pyperplan/task.py", line 125, in <listcomp>
    return [(op, op.apply(state)) for op in self.operators if op.applicable(state)]
  File "/home/daineto/CostFOND/planner/pyperplan/pyperplan/task.py", line 63, in apply
    return (state - self.del_effects) | self.add_effects
MemoryError
real 223.30
user 211.28
sys 15.07
